### ISSUE TITLE
Looks like you didn't finish this one...

### ISSUE THREAD

**Issue by soggybag** [alx-rg/titanic-data-challenges#4]
https://github.com/alx-rg/titanic-data-challenges/blob/82e7fa448285840e1584032e8238b5b667f08005/challenges-2.js#L78

Here is some pseudo code to complete the problem

- Define your histogram obj
- loop over all passengers
- - for each passenger check if that property value exists as a key on the histogram
- - - If the property exists add 1 to the value of the properrty
- - - else create the property on the histogram with a value of 1

**Comment by alx-rg** [comment]
You were correct, I hadn't yet finished it. It's done, thank you for pseudo code!
